/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AccountManager;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.AccountDirectarory;

/**
 *
 * @author ayushighia
 */
public class AccountMngWorkAreaJPanel extends javax.swing.JPanel {
      JPanel userProcessComtainer;
      AccountDirectarory accountdirectarory;
    /**
     * Creates new form AccountMngWorkAreaJPanel
     * @param comtainer
     * @param directarory
     */
    public AccountMngWorkAreaJPanel(JPanel comtainer, AccountDirectarory directarory) {
        initComponents();
        
        userProcessComtainer= comtainer;
        accountdirectarory = directarory;
        
       
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateAccount = new javax.swing.JButton();
        btbManageAccount = new javax.swing.JButton();

        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });

        btbManageAccount.setText("Manage Account");
        btbManageAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbManageAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbManageAccount))
                .addGap(0, 384, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnCreateAccount)
                .addGap(12, 12, 12)
                .addComponent(btbManageAccount)
                .addContainerGap(312, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        // TODO add your handling code here:
        CreateAccountJPanel panel= new CreateAccountJPanel(userProcessComtainer, accountdirectarory);
        userProcessComtainer.add("CreateAccountJPanel", panel);
        
        CardLayout layout = (CardLayout) userProcessComtainer.getLayout();
        layout.next(userProcessComtainer);
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void btbManageAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbManageAccountActionPerformed
        // TODO add your handling code here:
        ManageAccountsJPanel panel= new ManageAccountsJPanel(userProcessComtainer, accountdirectarory);
        userProcessComtainer.add("ViewAccountJPanel", panel);
        
        CardLayout layout = (CardLayout) userProcessComtainer.getLayout();
        layout.next(userProcessComtainer);
    }//GEN-LAST:event_btbManageAccountActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbManageAccount;
    private javax.swing.JButton btnCreateAccount;
    // End of variables declaration//GEN-END:variables
}
