/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AccountManager;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Account;
import model.AccountDirectarory;


/**
 *
 * @author ayushighia
 */
public class ManageAccountsJPanel extends javax.swing.JPanel {
    JPanel userProcessComtainer;
    AccountDirectarory accountDirectarory;

    /**
     * Creates new form ManageAccountsJPanel
     * @param Comtainer
     * @param directarory
     */
    public ManageAccountsJPanel(JPanel Comtainer, AccountDirectarory directarory) {
        userProcessComtainer=Comtainer;
        accountDirectarory = directarory;
      
        
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnViewDetails = new javax.swing.JButton();
        btnDeleteAccount = new javax.swing.JButton();
        btbSave = new javax.swing.JButton();
        txtSearchBox = new javax.swing.JTextField();
        btbBack = new javax.swing.JButton();

        lblTitle.setText("Manage Account");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Account"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnDeleteAccount.setText("Delete Account");
        btnDeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAccountActionPerformed(evt);
            }
        });

        btbSave.setText("Search");
        btbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbSaveActionPerformed(evt);
            }
        });

        btbBack.setText("<<< Back");
        btbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btbBack)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(228, 228, 228))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnViewDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDeleteAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btbSave)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btbBack)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDetails)
                    .addComponent(btbSave)
                    .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDeleteAccount)
                .addGap(113, 113, 113))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbBackActionPerformed
        // TODO add your handling code here:
         
          userProcessComtainer.remove(this);
          CardLayout layout = (CardLayout) userProcessComtainer.getLayout();
          layout.previous(userProcessComtainer);
        
    }//GEN-LAST:event_btbBackActionPerformed

    private void btnDeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAccountActionPerformed

        int selectedRow = jTable2.getSelectedRow();
        if(selectedRow>=1){
        
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult= JOptionPane.showConfirmDialog(null, "Are you sure?", "Warning",dialogButton);
            if(dialogResult==JOptionPane.YES_OPTION){
            
                Account selectedAccount =(Account) jTable2.getValueAt(selectedRow,0);
                accountDirectarory.deleteAccount(selectedAccount);
                populateTable();
                
            
            }
            else{
            
                JOptionPane.showMessageDialog(null, "Please select an Account");
            
            }
        
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteAccountActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed

        int selectedRow=jTable2.getSelectedRow();
        if(selectedRow>=1){
       
            
            Account selectedAccount =(Account) jTable2.getValueAt(selectedRow,0);
            
            ViewAccountJPanel panel = new ViewAccountJPanel(userProcessComtainer,accountDirectarory,selectedAccount);
            userProcessComtainer.add("ViewAccountJPanel",panel);
            CardLayout layout = (CardLayout) userProcessComtainer.getLayout();
            layout.previous(userProcessComtainer);
            
          
        }
        
        else{
            
                JOptionPane.showMessageDialog(null, "Please select an Account");
            
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbSaveActionPerformed

        if(!txtSearchBox.getText().isBlank()){
            String accountNumber = txtSearchBox.getText();
            Account foundAccount = accountDirectarory.searchAccount(accountNumber);
            
            if(foundAccount!=null){
            
                ViewAccountJPanel panel = new ViewAccountJPanel(userProcessComtainer,accountDirectarory,foundAccount);
                userProcessComtainer.add("ViewAccountJPanel",panel);
                CardLayout layout = (CardLayout) userProcessComtainer.getLayout();
                layout.previous(userProcessComtainer);
                
            }
            
            else{
                JOptionPane.showMessageDialog(null, "Account not found. Please check and try again");
                
            
            }
           
        
        }else{JOptionPane.showMessageDialog(null, "Please type account number to view");}

            // TODO add your handling code here:
    }//GEN-LAST:event_btbSaveActionPerformed

    
    
private void populateTable(){

    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    model.setRowCount(0);
    
    for(Account acc:accountDirectarory.getAccounts()){
    
        Object[] row = new Object[4];
        row[0]=acc;
        row[1]=acc.getAccountNumber();
        row[2]=acc.getRoutingNumber();
        row[3]=acc.getBalance();
        
        model.addRow(row);
    
    }



}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbBack;
    private javax.swing.JButton btbSave;
    private javax.swing.JButton btnDeleteAccount;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtSearchBox;
    // End of variables declaration//GEN-END:variables
}
